wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1711476956.0
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 16
      - 23
      - 62
      4: 3.10.12
      5: 0.16.5
      8:
      - 1
      - 5
      13: linux-x86_64
